version: '3.8'
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: serverperrihijos
        command: npm start
        ports:
            - 5000:5000
    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      image: tiendaperrihijos
      command: npm start
      ports:
        - 3000:3000
