export const authConstantes = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}


export const authConstantesC = {
    LOGIN_REQUESTC: 'LOGIN_REQUESTC',
    LOGIN_FAILUREC: 'LOGIN_FAILUREC',
    LOGIN_SUCCESSC: 'LOGIN_SUCESSC',
    LOGOUT_REQUESTC: 'LOGOUT_REQUESTC',
    LOGOUT_SUCCESSC: 'LOGOUT_SUCCESSC',
    LOGOUT_FAILUREC: 'LOGOUT_FAILUREC'
}


export const clientConstantes ={
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
    USER_REGISTER_REQUESTC: 'USER_REGISTER_REQUESTC',
    USER_REGISTER_SUCCESSC: 'USER_REGISTER_SUCCESSC',
    USER_REGISTER_FAILUREC: 'USER_REGISTER_FAILUREC'
}

export const categoriaConstantes = {
    GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
    GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
    GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
    ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",
}

export const datosInicialesConstantes = {
    GET_ALL_INITIAL_DATA_REQUEST: "GET_ALL_INITIAL_DATA_REQUEST",
    GET_ALL_INITIAL_DATA_SUCCESS: "GET_ALL_INITIAL_DATA_SUCCESS",
    GET_ALL_INITIAL_DATA_FAILURE: "GET_ALL_INITIAL_DATA_FAILURE",
}

export const productosConstantes = {
    GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",

}

export const productosTiendaConstantes = {
    GET_PRODUCTS_SLUG:"GET_PRODUCTS_SLUG",
    GET_ALL_DETAILS_REQUEST: "GET_ALL_DETAILS_REQUEST",
    GET_ALL_DETAILS_SUCCESS: "GET_ALL_DETAILS_SUCCESS",
    GET_ALL_DETAILS_FAILURE: "GET_ALL_DETAILS_FAILURE",
}

export const carritoConstantes = {
    ADD_CARRITO_REQUEST : "ADD_CARRITO_REQUEST",
    ADD_CARRITO: "ADD_CARRITO",
    ADD_CARRITO_FAILURE: "ADD_CARRITO_FAILURE",
    RESET_CARRITO: "RESET_CARRITO"
}